# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - master
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "rccoder"
- git config --global user.email "rccoder.net@gmail.com"
# 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
# 不用yarn的话这里改成 npm i 即可
- yarn
script:
- yarn run autoPub
after_success:
- git push https://$REPO_TOKEN@github.com:rccoder/AppVeygorTest gh-pages --force
