# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - master
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "rccoder"
- git config --global user.email "rccoder.net@gmail.com"
- export PATH=$HOME/.yarn/bin:$PATH
install:
- npm i
script:
- npm run clean
- npm run build
- cp CNAME _book
- cd _book
- npm run offline
- git init
- git commit --allow-empty -m 'update book'
- git checkout -b gh-pages && touch .nojekyll
- git add .
- git commit -am 'update book'
after_success:
- git push https://$REPO_TOKEN@github.com/rccoder/AppVeygorTest gh-pages --force
