language: node_js
node_js: stable
branches:
  only:
  - master
before_install:
- git config --global user.name "rccoder"
- git config --global user.email "rccoder.net@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- npm install npm@latest -g
- npm i
script:
- npm run clean
- npm run build
- cp CNAME _book
- cd _book
- git init
- git commit --allow-empty -m 'update book'
- git checkout -b gh-pages && touch .nojekyll
- git add .
- git commit -am 'update book'
after_success:
- git push https://$REPO_TOKEN@github.com/rccoder/AppVeygorTest gh-pages --force
